<?php

declare(strict_types=1);

/*
 * FeedbackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FeedbackAPILib\Tests;

use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): \FeedbackAPILib\FeedbackAPIClient
    {
        $clientBuilder = \FeedbackAPILib\FeedbackAPIClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        \FeedbackAPILib\FeedbackAPIClientBuilder $builder
    ): \FeedbackAPILib\FeedbackAPIClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        \FeedbackAPILib\FeedbackAPIClientBuilder $builder
    ): \FeedbackAPILib\FeedbackAPIClientBuilder {
        $timeout = getenv('FEEDBACK_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('FEEDBACK_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('FEEDBACK_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('FEEDBACK_API_LIB_ENVIRONMENT');
        $xRapidAPIKey = getenv('FEEDBACK_API_LIB_X_RAPID_API_KEY');

        if ($timeout !== false && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if ($environment !== false) {
            $builder->environment($environment);
        }

        if ($xRapidAPIKey !== false) {
            $builder->xRapidAPIKey($xRapidAPIKey);
        }

        return $builder;
    }
}
