<?php

declare(strict_types=1);

/*
 * FeedbackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FeedbackAPILib\Exceptions;

class BadRequestException extends ApiException
{
    /**
     * @var string
     */
    private $messageProperty;

    /**
     * @var \FeedbackAPILib\Models\Data|null
     */
    private $data;

    /**
     * Returns Message Property.
     */
    public function getMessageProperty(): string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     *
     * @maps message
     */
    public function setMessageProperty(string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns Data.
     */
    public function getData(): ?\FeedbackAPILib\Models\Data
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @maps data
     */
    public function setData(?\FeedbackAPILib\Models\Data $data): void
    {
        $this->data = $data;
    }
}
