<?php

declare(strict_types=1);

/*
 * FeedbackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FeedbackAPILib\Models;

use FeedbackAPILib\Utils\DateTimeHelper;
use stdClass;

class Feedback implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $rating;

    /**
     * @var bool|null
     */
    private $sentiment;

    /**
     * @var string[]|null
     */
    private $reasons;

    /**
     * @var string|null
     */
    private $suggestion;

    /**
     * @var string|null
     */
    private $page;

    /**
     * @var string|null
     */
    private $category;

    /**
     * @var string|null
     */
    private $apiOperationId;

    /**
     * @var string[]|null
     */
    private $tags;

    /**
     * @var string|null
     */
    private $userId;

    /**
     * @var string
     */
    private $id;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     */
    private $updatedAt;

    /**
     * @var string
     */
    private $userIP;

    /**
     * @var string
     */
    private $userAgent;

    /**
     * @param string $id
     * @param \DateTime $createdAt
     * @param string $userIP
     * @param string $userAgent
     */
    public function __construct(string $id, \DateTime $createdAt, string $userIP, string $userAgent)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->userIP = $userIP;
        $this->userAgent = $userAgent;
    }

    /**
     * Returns Rating.
     * Rating of the feedback.
     */
    public function getRating(): ?float
    {
        return $this->rating;
    }

    /**
     * Sets Rating.
     * Rating of the feedback.
     *
     * @maps rating
     */
    public function setRating(?float $rating): void
    {
        $this->rating = $rating;
    }

    /**
     * Returns Sentiment.
     * Sentiment of the feedback.
     */
    public function getSentiment(): ?bool
    {
        return $this->sentiment;
    }

    /**
     * Sets Sentiment.
     * Sentiment of the feedback.
     *
     * @maps sentiment
     */
    public function setSentiment(?bool $sentiment): void
    {
        $this->sentiment = $sentiment;
    }

    /**
     * Returns Reasons.
     * Reasons of the feedback.
     *
     * @return string[]|null
     */
    public function getReasons(): ?array
    {
        return $this->reasons;
    }

    /**
     * Sets Reasons.
     * Reasons of the feedback.
     *
     * @maps reasons
     *
     * @param string[]|null $reasons
     */
    public function setReasons(?array $reasons): void
    {
        $this->reasons = $reasons;
    }

    /**
     * Returns Suggestion.
     * Suggestion of the feedback.
     */
    public function getSuggestion(): ?string
    {
        return $this->suggestion;
    }

    /**
     * Sets Suggestion.
     * Suggestion of the feedback.
     *
     * @maps suggestion
     */
    public function setSuggestion(?string $suggestion): void
    {
        $this->suggestion = $suggestion;
    }

    /**
     * Returns Page.
     * Page of the feedback.
     */
    public function getPage(): ?string
    {
        return $this->page;
    }

    /**
     * Sets Page.
     * Page of the feedback.
     *
     * @maps page
     */
    public function setPage(?string $page): void
    {
        $this->page = $page;
    }

    /**
     * Returns Category.
     * Category of the feedback.
     */
    public function getCategory(): ?string
    {
        return $this->category;
    }

    /**
     * Sets Category.
     * Category of the feedback.
     *
     * @maps category
     */
    public function setCategory(?string $category): void
    {
        $this->category = $category;
    }

    /**
     * Returns Api Operation Id.
     * operationId of the API.
     */
    public function getApiOperationId(): ?string
    {
        return $this->apiOperationId;
    }

    /**
     * Sets Api Operation Id.
     * operationId of the API.
     *
     * @maps apiOperationId
     */
    public function setApiOperationId(?string $apiOperationId): void
    {
        $this->apiOperationId = $apiOperationId;
    }

    /**
     * Returns Tags.
     * Any list of tags to group feedbacks by.
     *
     * @return string[]|null
     */
    public function getTags(): ?array
    {
        return $this->tags;
    }

    /**
     * Sets Tags.
     * Any list of tags to group feedbacks by.
     *
     * @maps tags
     *
     * @param string[]|null $tags
     */
    public function setTags(?array $tags): void
    {
        $this->tags = $tags;
    }

    /**
     * Returns User Id.
     * Unique identifier of the user.
     */
    public function getUserId(): ?string
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     * Unique identifier of the user.
     *
     * @maps userId
     */
    public function setUserId(?string $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns Id.
     * Unique identifier of the feedback.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Unique identifier of the feedback.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created At.
     * Date of the feedback creation.
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * Date of the feedback creation.
     *
     * @required
     * @maps createdAt
     * @factory \FeedbackAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     * Date of the feedback update.
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     * Date of the feedback update.
     *
     * @maps updatedAt
     * @factory \FeedbackAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns User IP.
     * IP address of the user.
     */
    public function getUserIP(): string
    {
        return $this->userIP;
    }

    /**
     * Sets User IP.
     * IP address of the user.
     *
     * @required
     * @maps userIP
     */
    public function setUserIP(string $userIP): void
    {
        $this->userIP = $userIP;
    }

    /**
     * Returns User Agent.
     * User agent of the device.
     */
    public function getUserAgent(): string
    {
        return $this->userAgent;
    }

    /**
     * Sets User Agent.
     * User agent of the device.
     *
     * @required
     * @maps userAgent
     */
    public function setUserAgent(string $userAgent): void
    {
        $this->userAgent = $userAgent;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->rating)) {
            $json['rating']         = $this->rating;
        }
        if (isset($this->sentiment)) {
            $json['sentiment']      = $this->sentiment;
        }
        if (isset($this->reasons)) {
            $json['reasons']        = $this->reasons;
        }
        if (isset($this->suggestion)) {
            $json['suggestion']     = $this->suggestion;
        }
        if (isset($this->page)) {
            $json['page']           = $this->page;
        }
        if (isset($this->category)) {
            $json['category']       = $this->category;
        }
        if (isset($this->apiOperationId)) {
            $json['apiOperationId'] = $this->apiOperationId;
        }
        if (isset($this->tags)) {
            $json['tags']           = $this->tags;
        }
        if (isset($this->userId)) {
            $json['userId']         = $this->userId;
        }
        $json['id']                 = $this->id;
        $json['createdAt']          = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        if (isset($this->updatedAt)) {
            $json['updatedAt']      = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        }
        $json['userIP']             = $this->userIP;
        $json['userAgent']          = $this->userAgent;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
