<?php

declare(strict_types=1);

/*
 * FeedbackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FeedbackAPILib;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager extends CoreAuth implements CustomHeaderAuthenticationCredentials
{
    private $xRapidAPIKey;

    /**
     * Returns an instance of this class.
     *
     * @param string $xRapidAPIKey Your Rapid API Key
     */
    public function __construct(string $xRapidAPIKey)
    {
        parent::__construct(HeaderParam::init('X-RapidAPI-Key', $xRapidAPIKey)->required());
        $this->xRapidAPIKey = $xRapidAPIKey;
    }

    /**
     * String value for xRapidAPIKey.
     */
    public function getXRapidAPIKey(): string
    {
        return $this->xRapidAPIKey;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xRapidAPIKey Your Rapid API Key
     */
    public function equals(string $xRapidAPIKey): bool
    {
        return $xRapidAPIKey == $this->xRapidAPIKey;
    }
}
