<?php

declare(strict_types=1);

/*
 * FeedbackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FeedbackAPILib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Production server
     */
    public const PRODUCTION = 'production';
}
